Select({
  id: 'pickerList',
  flexGrow: 1,
  options: [],
  backgroundColor: config.theme.bg,
  focusedBackgroundColor: config.theme.bg,
  textColor: config.theme.fg,
  focusedTextColor: config.theme.fg,
  descriptionColor: config.theme.muted,
  selectedBackgroundColor: config.theme.selection,
  selectedTextColor: config.theme.fg,
  selectedDescriptionColor: config.theme.muted,
  showDescription: true,
  showSelectionIndicator: true,
});
